### ISSUE TITLE
Add db entry on rating change (add)

### ISSUE THREAD

**Issue by busykoala** [busykoala/paragliding_weather#33]
When the rating is set (rating changes) a new db entry should be made.
The db entry should contain:
- current timestamp
- timestamp of data used for prediction
- location
- rating

With these db entries we can then train a model for various predictions.

**Comment by mbaechtold** [comment]
Has this issue been resolved through the pull request #39?

GitHub did not close this issue when the pull request was merged because GitHub does not listen on the keyword `closing #xy`, it only listens on the keywords listed in https://help.github.com/articles/closing-issues-using-keywords/:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/28220/47085252-5ad7b680-d216-11e8-928b-5856ef3eebca.png">

**Comment by busykoala** [comment]
Yes indeed this issues should have been closed by that. Thanks for the note.
I'm gonna close the issue.
